proof-of-concept: Go wasi
OffchainLabs/stylus pull request #187
Opened 2023-12-14 20:28 UTC by tsahee

2024-01-26 01:39 UTC, tsahee commented on arbitrator/arbutil/src/evm/req.rs
> +// For license information, see https://github.com/OffchainLabs/nitro/blob/master/LICENSE
note: this is based on the old js.rs file, but seems like changed enough that github doesn't recognize it.

2024-01-26 01:39 UTC, tsahee commented on arbitrator/arbutil/src/evm/req.rs
> +impl<T: RequestHandler> EvmApi for EvmApiRequestor<T> {
Note: this is now the only implementation of EvmApi trait.

2024-01-26 01:39 UTC, tsahee commented on arbitrator/jit/src/arbcompress.rs
note: I am thinking of merging this code with that of wasm-libraries/brotli - but not high prio

2024-01-26 01:39 UTC, tsahee commented on arbitrator/jit/src/goenv.rs
> +
note: this file is based on the original gostack.rs.
I plan to eventually have this in a trait that will allow sharing more code bewteen jit and wasm-libraries.

2024-01-26 01:39 UTC, tsahee commented on arbitrator/jit/src/program.rs
> +// Copyright 2022-2023, Offchain Labs, Inc.
note: bthis is based on/replaces previous user submodule

2024-01-26 01:39 UTC, tsahee commented on arbitrator/jit/src/wasip1_stub.rs
> +// For license information, see https://github.com/nitro/blob/master/LICENSE
note: near future plan: merge this code with wasm-libraries/wasi-stub

2024-01-26 01:39 UTC, tsahee commented on arbitrator/prover/src/error_guard.rs
> +use std::fmt::{self, Display};
note: enable/disable error guard is not needed. Instead, we use "cothread" boolean which does the same

2024-01-26 01:40 UTC, tsahee commented on arbitrator/arbutil/src/evm/req.rs
> +impl<T: RequestHandler> EvmApi for EvmApiRequestor<T> {
(except for the test one)

2024-02-01 06:06 UTC, rachel-bousfield requested changes
Nice draft!

I need to review more, but wanted to provide some feedback earlier on.

I know this is an early but something that'd help would be docstrings. There's a lot of subtle stuff happening and across multiple files so any kind of documentation in the code or in notion would be helpful.

That and when the repo builds, I'll be able to try more things out. In any case here's a few comments I hope will make this even better :)

2024-02-01 06:06 UTC, rachel-bousfield commented on arbos/programs/api.go
> +			return []byte{1}, cost
In the previous model, we got to work with nicely typed closures. Sure there was byte-munging, but it was at the type level vs baked into the business logic. Let's look at this function but the reasoning applies across all the hostios.
```go
setBytes32 := func(key, value common.Hash) (uint64, error) {
    if tracingInfo != nil {
        tracingInfo.RecordStorageSet(key, value)
    }
    if readOnly {
        return 0, vm.ErrWriteProtection
    }
    cost := vm.WasmStateStoreCost(db, actingAddress, key, value)
    db.SetState(actingAddress, key, value)
    return cost, nil
}
```

In the new code, Rust and Go have to agree on special bytes and structure. This is a bit dangerous in constructs where the shape is variable length like in the contract calling hostios, but even in this simpler hostio we get an example.

In the old model, we could nicely pass `vm.ErrWriteProtection` back to the Rust side. Here though we have to set a flag byte, and then expect Rust treat it the same way. It turns out that Rust now just says "set_bytes32 failed", but that's not exactly what happened. We hit a write protection, which users can do by static calling into a contract that performs a write.

It's really hard to see this kind of nuance across the Rust <=> Go interop line when all these concepts are happening at the same time. I think we need to find a way to replace this switch statement with something more type-aware. A reader pattern could be a first start, where instead of reading offsets explicitly you read from a stream of bytes one type at a time. We do this in a few places like `TestProgramEvmData`. In terms of making sure the length is right, you could error if the stream runs out early or has extra bytes at the end.

2024-02-01 06:06 UTC, rachel-bousfield commented on arbos/programs/wasm.go
> +	errBuf := make([]byte, 1024)
In debug mode these can be very long, I wouldn't use a fixed size

2024-02-01 06:06 UTC, rachel-bousfield commented on arbitrator/arbutil/src/evm/req.rs
> +        request.extend_from_slice(&gas.to_be_bytes());
Here and elsewhere you can do
```rs
request.extend(contract)
```

They're the same just `extend_from_slice` is going to be deprecated and `extend` is prettier :)

2024-02-01 06:06 UTC, rachel-bousfield commented on arbitrator/arbutil/src/evm/req.rs
> +    last_call_result: Vec<u8>,
In this model, are we able to return data from Go => Rust without the copy?

For example, the `read_return_data` hostio should ideally just pass the pointer from Go back to Rust (Geth takes special care of that slice so that it's zero-copy).

2024-02-01 06:06 UTC, rachel-bousfield commented on arbitrator/arbutil/src/evm/req.rs
> +                match String::from_utf8(res) {
```rs
String::from_utf8_lossy(&res[1...])
String::from_utf8(res).unwrap_or("create_response_malformed".into())

// or even
if let Ok(str) = String::from_utf8(res) {
    err_string = str
}
```

2024-02-01 06:06 UTC, rachel-bousfield commented on arbitrator/arbutil/src/evm/req.rs
> +        return (Ok(address), self.last_call_result.len() as u32, cost);
You can drop the `return` here

2024-02-01 06:06 UTC, rachel-bousfield commented on arbitrator/arbutil/src/evm/req.rs
> +        };
Maybe
```rs
self.last_call_result = (res.len() > 21)
    .then(|| res.drain(21..).collect())
    .unwrap_or_default();
```

2024-02-01 06:06 UTC, rachel-bousfield commented on arbitrator/arbutil/src/evm/req.rs
> +            .handler
`EvmApiRequestor` should probably implement `Deref<RequestHandler>` and `DerefMut<RequestHandler>` to make these kinds of expressions shorter

2024-02-01 06:06 UTC, rachel-bousfield commented on arbitrator/arbutil/src/evm/req.rs
> +        data[offset..size].to_vec()
We should avoid this copy and instead return a slice

2024-02-01 06:06 UTC, rachel-bousfield commented on arbitrator/arbutil/src/evm/req.rs
> +            Err(eyre!(
`bail!()`

Also I like
```rs
match cond {
    true => expr,
    false => expr,
}
```

It's pretty with verum and falsum as ligatures :)

2024-02-01 06:06 UTC, rachel-bousfield commented on arbitrator/jit/src/program.rs
> +    let mut genv = GoEnv::new(&mut env);
Let's call it `go_env` or `env`

2024-02-01 06:06 UTC, rachel-bousfield commented on arbitrator/jit/src/stylus_backend.rs
> +                req_type: req_type as u32 + 0x10000000,
We should document `0x10000000`

2024-02-01 06:06 UTC, rachel-bousfield commented on arbitrator/wasm-libraries/user-host/src/program.rs
> +        return Err(eyre!("recording start ink while proving").into())
`bail!`

2024-02-07 02:48 UTC, tsahee commented on arbos/programs/api.go
> +			return []byte{1}, cost
as discussed - kept the switch statement for encoding, decoding only

2024-02-07 17:53 UTC, tsahee commented on arbitrator/arbutil/src/evm/req.rs
> +        };
improved it with pre-draining.

2024-02-07 20:20 UTC, tsahee commented on arbitrator/arbutil/src/evm/req.rs
> +        data[offset..size].to_vec()
will be implemented later

2024-02-07 20:20 UTC, tsahee commented on arbitrator/arbutil/src/evm/req.rs
> +    last_call_result: Vec<u8>,
will be implemented later

2024-02-07 20:20 UTC, tsahee commented on arbitrator/jit/src/program.rs
> +    let mut genv = GoEnv::new(&mut env);
renamed class to CallerEnv and var to caller_env..
it's not really go specific now

2024-02-14 23:01 UTC, tsahee commented on arbitrator/arbutil/src/evm/req.rs
> +            .handler
implemented in the next PR by having a handle_request in this func

2024-02-14 23:02 UTC, tsahee commented on arbitrator/wasm-libraries/user-host/src/program.rs
> +        return Err(eyre!("recording start ink while proving").into())
bail here doesn't work because it returns the wrong error (need that into())

2024-03-08 23:23 UTC, merged